"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.typeDefs = void 0;
var apollo_server_1 = require("apollo-server");
exports.typeDefs = (0, apollo_server_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    type Player {\n        id: ID!\n        name: String!\n        ready: Boolean!\n    }\n\n    enum GameStatus {\n        NOT_STARTED\n        IN_PROGRESS\n        FINISHED\n    }\n\n    type Game {\n        id: ID!\n        players: [Player!]!\n        status: GameStatus\n    }\n\n    type LobbyOptions {\n        minPlayers: Int!\n        maxPlayers: Int!\n    }\n\n    type Lobby {\n        games: [Game!]!\n        playersNotJoined: [Player!]!\n        lobbyOptions: LobbyOptions\n    }\n\n    type Query {\n        lobby: Lobby!\n        allGames: [Game!]!\n        allPlayersNotJoined: [Player!]!\n    }\n\n    type Mutation {\n        createLobby(minPlayers: Int! maxPlayers: Int!): Lobby\n        createPlayer(name: String!): Player\n        createGame(playerID: ID!): Game\n        joinGame(gameID: ID! playerID: ID!): Game\n        toggleReady(playerID: ID!): Game\n        startGame(playerID: ID!): Game\n    }\n\n    type Subscription {\n        gameAdded: Game!\n        gameUpdated: Game!\n        gameStarted: Game!\n    }\n"], ["\n    type Player {\n        id: ID!\n        name: String!\n        ready: Boolean!\n    }\n\n    enum GameStatus {\n        NOT_STARTED\n        IN_PROGRESS\n        FINISHED\n    }\n\n    type Game {\n        id: ID!\n        players: [Player!]!\n        status: GameStatus\n    }\n\n    type LobbyOptions {\n        minPlayers: Int!\n        maxPlayers: Int!\n    }\n\n    type Lobby {\n        games: [Game!]!\n        playersNotJoined: [Player!]!\n        lobbyOptions: LobbyOptions\n    }\n\n    type Query {\n        lobby: Lobby!\n        allGames: [Game!]!\n        allPlayersNotJoined: [Player!]!\n    }\n\n    type Mutation {\n        createLobby(minPlayers: Int! maxPlayers: Int!): Lobby\n        createPlayer(name: String!): Player\n        createGame(playerID: ID!): Game\n        joinGame(gameID: ID! playerID: ID!): Game\n        toggleReady(playerID: ID!): Game\n        startGame(playerID: ID!): Game\n    }\n\n    type Subscription {\n        gameAdded: Game!\n        gameUpdated: Game!\n        gameStarted: Game!\n    }\n"])));
var templateObject_1;
